name: context_di
description: "Flutter Provider based Dependency Injection Tool"
version: 0.1.0-Preview
homepage: https://github.com/begekoth/context_di

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

