builders:
  feature:
    import: "package:context_di_generator/builder.dart"
    builder_factories: ["featureBuilder"]
    build_extensions: {".dart": [".feature.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]